[project]
name = "Stambaugh 1999 Replication"
description = "Replication of Stambaugh's Paper on Predictive Regressions (1999)"
maintainer = "Ashish Maheshwari & Omar Anabtawi"
contributors = ["Ashish Maheshwari & Omar Anabtawi"]
os_compatibility = ["Windows", "Linux", "macOS"]
build = """
module load anaconda3/3.11.4 TeXLive/2023
doit
"""

[notebooks]


[notebooks.01_example_notebook_interactive]
name = "Example Notebook Interactive"
description = "Example notebook for demonstrating how to construct a Chartbook notebook."
path = "_output/01_example_notebook_interactive.ipynb"




[dataframes]


[charts]

